version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - run: npm install
      - run: yarn ts-node .circleci/config.ts
      - continuation/continue:
          configuration_path: .circleci/processed-config.yml

workflows:
  setup:
    jobs:
      - setup
